### PR TITLE
Add temporary StatusCommand, fix addCommand bug, add addCommandParser tests 

### LINKED ISSUE #126: Can add the same module more than once
- Prevent adding module that has been added (both to the same semester and to different semesters) 
- Show error message if user tries to add module that has been added
- Disallow user to add the same module more than once at the same time, e.g `addModule y/1 s/1 c/CS1010 c/CS1010`

### PR DESCRIPTION
**Pull request by RomaRomama**
resolves #126

### CODE REVIEW

File: src/main/java/seedu/planner/commons/core/Messages.java [hunk 1]
```diff
@@ -12,4 +12,5 @@
 
     public static final String MESSAGE_INVALID_MODULES = "Invalid modules: %s";
     public static final String MESSAGE_INVALID_PARAMETERS = "Invalid parameters";
+    public static final String MESSAGE_EXISTED_MODULES = "Following module(s) already existed in the planner: %s";
```
Comment (GabrielYik) [inline src/main/java/seedu/planner/commons/core/Messages.java]: `existed` to `exist`

File: src/main/java/seedu/planner/logic/commands/StatusCommand.java [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+/**
+ * Display the credit count status of the user in the planner
+ */
+public class StatusCommand extends Command {
+
+    public static final String COMMAND_WORD = "status";
+    private static final String CREDITS_LEFT = "Total credits left to fulfill course requirement: ";
+
+    private static final int CREDIT_TO_GRADUATE = 160;
+    private static final int NUM_OF_SEMESTER = 8;
```
Comment (GabrielYik) [inline src/main/java/seedu/planner/logic/commands/StatusCommand.java]: I think we should reuse the `MAX_NUMBER_SEMESTERS` from `ModulePlanner`

File: src/main/java/seedu/planner/logic/commands/StatusCommand.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+        int totalCreditCount = 0;
+        for (int i = 0; i < NUM_OF_SEMESTER; i++) {
+            for (Module module : model.getTakenModuleList(i)) {
+                creditCounts[i] += module.getCreditCount();
+            }
+            totalCreditCount += creditCounts[i];
+        }
+
+        StringBuilder sb = new StringBuilder();
+        for (int i = 1; i < NUM_OF_SEMESTER; i++) {
```
Comment (GabrielYik) [inline src/main/java/seedu/planner/logic/commands/StatusCommand.java]: `<` to `<=`
